#include <iostream>
using namespace std;
int main()
{
	string name,clas;
	int age;
	long id;
	cout << "First student\n";
	cout << "Enter the name of the student:\n";
	cin >> name;
	cout << "Enter the student's class:\n";
	cin >> clas;
	cout << "Enter the age of the student:\n";
	cin >> age;
	cout << "Enter the student id:\n";
	cin >> id;
	cout << "\n*************************************************\n";
	cout << "First student:\n";
	cout << "Name: " << name << endl;
	cout << "Class: " << clas << endl;
	cout << "Age: " << age << endl;
	cout << "ID: " << id << endl;
	cout << "\n*************************************************\n";
	cout << "Second student\n";
	cout << "Enter the name of the student:\n";
	cin >> name;
	cout << "Enter the student's class:\n";
	cin >> clas;
	cout << "Enter the age of the student:\n";
	cin >> age;
	cout << "Enter the student id:\n";
	cin >> id;
	cout << "\n*************************************************\n";
	cout << "Second student:\n";
	cout << "Name: " << name << endl;
	cout << "Class: " << clas << endl;
	cout << "Age: " << age << endl;
	cout << "ID: " << id << endl;
	cout << "\n*************************************************\n";
	cout << "Third student\n";
	cout << "Enter the name of the student:\n";
	cin >> name;
	cout << "Enter the student's class:\n";
	cin >> clas;
	cout << "Enter the age of the student:\n";
	cin >> age;
	cout << "Enter the student id:\n";
	cin >> id;
	cout << "\n*************************************************\n";
	cout << "Third student:\n";
	cout << "Name: " << name << endl;
	cout << "Class: " << clas << endl;
	cout << "Age: " << age << endl;
	cout << "ID: " << id << endl;
	cout << "\n*************************************************\n";
	cout << "Fourth student\n";
	cout << "Enter the name of the student:\n";
	cin >> name;
	cout << "Enter the student's class:\n";
	cin >> clas;
	cout << "Enter the age of the student:\n";
	cin >> age;
	cout << "Enter the student id:\n";
	cin >> id;
	cout << "\n*************************************************\n";
	cout << "Fourth student:\n";
	cout << "Name: " << name << endl;
	cout << "Class: " << clas << endl;
	cout << "Age: " << age << endl;
	cout << "ID: " << id << endl;
	cout << "\n*************************************************\n";
	cout << "First student\n";
	cout << "Enter the name of the student:\n";
	cin >> name;
	cout << "Fifth the student's class:\n";
	cin >> clas;
	cout << "Enter the age of the student:\n";
	cin >> age;
	cout << "Enter the student id:\n";
	cin >> id;
	cout << "\n*************************************************\n";
	cout << "Fifth student:\n";
	cout << "Name: " << name << endl;
	cout << "Class: " << clas << endl;
	cout << "Age: " << age << endl;
	cout << "ID: " << id << endl;
	cout << "\n*************************************************\n";
	return 0;
}